### ISSUE TITLE
nitpick: you don't nead the "global"

### ISSUE THREAD

**Issue by Eh2406** [iliketomakestuff/PiSign#1]
Hi,

You mentioned that this is your first python so I thought you may want some code review. Love your work and just trying to help. If you want more nitpicks I can help :-P

You use the "global" keyword when you don't have to. The only one you need is `global pressed`. You nead it so you can `pressed=0`. Without global python guesses that you want to make a new local `pressed`. With the global python knows that you want to set the global one.

When you read a global (with or without the keyword) python guesses you want the value instead of getting a no variable error.

**Comment by iliketomakestuff** [comment]
Excellent, thanks for the info! Those have been fixed.

**Comment by Eh2406** [comment]
It basically looks good. Do you want more nitpicks?

Just trying to be friendly. :-)

**Comment by iliketomakestuff** [comment]
I know of several things that could be more efficient, but they'll have to wait for me.  Releasing the video today is a full time, all day affair.  
Feel free to fork and update though, I'll happily merge the changes.
